### ISSUE TITLE
Should probably go into `etc/parameters.csv` or into `raw`

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/audersetinterrog#1]
In this case, where the dataset is developed **with** the author of the raw data, the parameter descriptions (see
https://github.com/cldf-datasets/audersetinterrog/blob/7d5c51d9ad3876baede4260fa77f758803e5abe3/cldfbench_audersetinterrog.py#L10-L18 ) should probably go into `raw` - otherwise in `etc`.

**Comment by chrzyki** [comment]
Thanks, will move this.
