### ISSUE TITLE
Release after Glottolog Medieval Greek PR has been merged

### ISSUE THREAD

**Issue by chrzyki** [cldf-datasets/audersetinterrog#3]

**Comment by xrotwang** [comment]
In master now: https://github.com/glottolog/glottolog/blob/master/languoids/tree/indo1319/grae1234/gree1276/east2798/koin1234/medi1251/md.ini
Will be released with Glottolog v4.2

**Comment by chrzyki** [comment]
Thanks! I'll get this ready then.
